FROM docker.n8n.io/n8nio/n8n
USER root
RUN apk add --no-cache bash

COPY --chmod=755 ./docker/images/osc/osc-entrypoint.sh /osc-entrypoint.sh

USER node
ENV N8N_PORT=8080
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_RUNNERS_MODE=external
ENV N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0

ENTRYPOINT ["/osc-entrypoint.sh"]

